creatures = [
    "aardvark",
    "aardvark man",
    "acorn fly",
    "adder",
    "adder man",
    "albatross",
    "albatross man",
    "alligator",
    "alligator man",
    "alligator snapping turtle",
    "alpaca",
    "amethyst man",
    "amphibian man",
    "anaconda",
    "anaconda man",
    "anchovy",
    "angel",
    "angelshark",
    "animated dead",
    "anole",
    "anole man",
    "ant",
    "antman",
    "armadillo",
    "armadillo man",
    "axolotl",
    "axolotl man",
    "aye-aye",
    "aye-aye man",
    "badger",
    "badger man",
    "banded knifefish",
    "bark scorpion",
    "bark scorpion man",
    "barn owl",
    "barn owl man",
    "basking shark",
    "bat",
    "bat man",
    "bat ray",
    "beak dog",
    "beaver",
    "beaver man",
    "beetle",
    "beetle man",
    "bilou",
    "black bear",
    "black bear man",
    "black bullhead",
    "black mamba",
    "black mamba man",
    "black-crested gibbon",
    "black-handed gibbon",
    "blacktip reef shark",
    "blind cave bear",
    "blind cave ogre",
    "blizzard man",
    "blood gnat",
    "blood man",
    "blue jay",
    "blue peafowl",
    "blue shark",
    "bluefin tuna",
    "bluefish",
    "bluejay man",
    "bobcat",
    "bobcat man",
    "bogeyman",
    "bonobo",
    "bronze colossus",
    "brook lamprey",
    "brown bullhead",
    "brown recluse spider",
    "brown recluse spider man",
    "bugbat",
    "bull shark",
    "bumblebee",
    "bushmaster",
    "bushmaster man",
    "bushtit",
    "bushtit man",
    "buzzard",
    "buzzard man",
    "camel",
    "cap hopper",
    "captured live fish",
    "capuchin",
    "capuchin man",
    "capybara",
    "capybara man",
    "cardinal",
    "cardinal man",
    "carp",
    "cassowary",
    "cassowary man",
    "cat",
    "cave blob",
    "cave crocodile",
    "cave dragon",
    "cave fish",
    "cave fish man",
    "cave floater",
    "cave lobster",
    "cave spider",
    "cave swallow",
    "cave swallow man",
    "cavy",
    "centaur",
    "chameleon",
    "chameleon man",
    "char",
    "cheetah",
    "cheetah man",
    "chicken",
    "chimera",
    "chimpanzee",
    "chinchilla",
    "chinchilla man",
    "chipmunk",
    "chipmunk man",
    "clown loach",
    "clownfish",
    "coati",
    "coati man",
    "cockatiel",
    "cockatiel man",
    "cod",
    "coelacanth",
    "common skate",
    "common snapping turtle",
    "conger eel",
    "copperhead snake",
    "copperhead snake man",
    "cougar",
    "cougar man",
    "cow",
    "coyote",
    "coyote man",
    "crab",
    "crab man",
    "creeping eye",
    "creepy crawler",
    "crow",
    "crow man",
    "crundle",
    "cuttlefish",
    "cuttlefish man",
    "cyclops",
    "damselfly",
    "damselfly man",
    "dark gnome",
    "deer",
    "deer man",
    "demon",
    "demon rat",
    "desert tortoise",
    "desert tortoise man",
    "dingo",
    "dingo man",
    "dog",
    "donkey",
    "dragon",
    "dragonfly",
    "dragonfly man",
    "draltha",
    "drunian",
    "duck",
    "dwarf",
    "eagle",
    "eagle man",
    "echidna",
    "echidna man",
    "elephant",
    "elephant man",
    "elephant seal",
    "elephant seal man",
    "elf",
    "elk",
    "elk bird",
    "elk man",
    "emperor penguin",
    "emu",
    "emu man",
    "ettin",
    "experiment",
    "fairy",
    "fire imp",
    "fire man",
    "fire snake",
    "firefly",
    "firefly man",
    "flesh ball",
    "floating guts",
    "flounder",
    "fluffy wambler",
    "fly",
    "fly man",
    "flying squirrel",
    "flying squirrel man",
    "foul blendec",
    "fox",
    "fox man",
    "fox squirrel",
    "frill shark",
    "gabbro man",
    "gazelle",
    "gazelle man",
    "ghost",
    "giant",
    "giant aardvark",
    "giant adder",
    "giant albatross",
    "giant alligator",
    "giant anaconda",
    "giant anole",
    "giant armadillo",
    "giant axolotl",
    "giant aye-aye",
    "giant badger",
    "giant bark scorpion",
    "giant barn owl",
    "giant bat",
    "giant beaver",
    "giant beetle",
    "giant black bear",
    "giant black mamba",
    "giant bluejay",
    "giant bobcat",
    "giant brown recluse spider",
    "giant bushmaster",
    "giant bushtit",
    "giant buzzard",
    "giant capuchin",
    "giant capybara",
    "giant cardinal",
    "giant cassowary",
    "giant cave spider",
    "giant cave swallow",
    "giant cave toad",
    "giant chameleon",
    "giant cheetah",
    "giant chinchilla",
    "giant chipmunk",
    "giant coati",
    "giant cockatiel",
    "giant copperhead snake",
    "giant cougar",
    "giant coyote",
    "giant crab",
    "giant crow",
    "giant cuttlefish",
    "giant damselfly",
    "giant deer",
    "giant desert scorpion",
    "giant desert tortoise",
    "giant dingo",
    "giant dragonfly",
    "giant eagle",
    "giant earthworm",
    "giant echidna",
    "giant elephant",
    "giant elephant seal",
    "giant elk",
    "giant emu",
    "giant firefly",
    "giant fly",
    "giant flying squirrel",
    "giant fox",
    "giant gazelle",
    "giant gila monster",
    "giant giraffe",
    "giant grackle",
    "giant grasshopper",
    "giant gray langur",
    "giant gray squirrel",
    "giant great horned owl",
    "giant green tree frog",
    "giant grey parrot",
    "giant grizzly bear",
    "giant groundhog",
    "giant grouper",
    "giant hamster",
    "giant hare",
    "giant harp seal",
    "giant hedgehog",
    "giant hippo",
    "giant hoary marmot",
    "giant honey badger",
    "giant hornbill",
    "giant horseshoe crab",
    "giant hyena",
    "giant ibex",
    "giant iguana",
    "giant impala",
    "giant jackal",
    "giant jaguar",
    "giant jumping spider",
    "giant kakapo",
    "giant kangaroo",
    "giant kea",
    "giant kestrel",
    "giant king cobra",
    "giant kingsnake",
    "giant kiwi",
    "giant koala",
    "giant leech",
    "giant leopard",
    "giant leopard gecko",
    "giant leopard seal",
    "giant lion",
    "giant lion tamarin",
    "giant lizard",
    "giant loon",
    "giant lorikeet",
    "giant louse",
    "giant lynx",
    "giant magpie",
    "giant mandrill",
    "giant mantis",
    "giant masked lovebird",
    "giant mink",
    "giant mole",
    "giant monarch butterfly",
    "giant mongoose",
    "giant monitor lizard",
    "giant moon snail",
    "giant moose",
    "giant mosquito",
    "giant moth",
    "giant mountain goat",
    "giant muskox",
    "giant narwhal",
    "giant nautilus",
    "giant ocelot",
    "giant octopus",
    "giant olm",
    "giant one-humped camel",
    "giant opossum",
    "giant orca",
    "giant oriole",
    "giant osprey",
    "giant ostrich",
    "giant otter",
    "giant pangolin",
    "giant parakeet",
    "giant peach-faced lovebird",
    "giant penguin",
    "giant peregrine falcon",
    "giant platypus",
    "giant polar bear",
    "giant pond turtle",
    "giant porcupine",
    "giant puffin",
    "giant python",
    "giant raccoon",
    "giant rat",
    "giant rattlesnake",
    "giant raven",
    "giant red panda",
    "giant red squirrel",
    "giant red-winged blackbird",
    "giant rhesus macaque",
    "giant rhinoceros",
    "giant roach",
    "giant saltwater crocodile",
    "giant skink",
    "giant skunk",
    "giant sloth",
    "giant sloth bear",
    "giant slug",
    "giant snail",
    "giant snapping turtle",
    "giant snowy owl",
    "giant sparrow",
    "giant sperm whale",
    "giant spider monkey",
    "giant sponge",
    "giant stoat",
    "giant swan",
    "giant tapir",
    "giant thrips",
    "giant tick",
    "giant tiger",
    "giant toad",
    "giant tortoise",
    "giant tortoise man",
    "giant two-humped camel",
    "giant vulture",
    "giant walrus",
    "giant warthog",
    "giant weasel",
    "giant white stork",
    "giant wild boar",
    "giant wolf",
    "giant wolverine",
    "giant wombat",
    "giant wren",
    "gigantic panda",
    "gigantic squid",
    "gigantic tortoise",
    "gila monster",
    "gila monster man",
    "giraffe",
    "giraffe man",
    "glasseye",
    "goat",
    "goblin",
    "goose",
    "gorilla",
    "gorlak",
    "grackle",
    "grackle man",
    "grasshopper",
    "grasshopper man",
    "gray gibbon",
    "gray langur",
    "gray langur man",
    "gray squirrel",
    "gray squirrel man",
    "great barracuda",
    "great horned owl",
    "great horned owl man",
    "great white shark",
    "green devourer",
    "green tree frog",
    "green tree frog man",
    "gremlin",
    "grey parrot",
    "grey parrot man",
    "griffon",
    "grimeling",
    "grizzly bear",
    "grizzly bear man",
    "groundhog",
    "groundhog man",
    "guineafowl",
    "guppy",
    "hagfish",
    "hake",
    "halibut",
    "hammerhead shark",
    "hamster",
    "hamster man",
    "hare",
    "hare man",
    "harp seal",
    "harp seal man",
    "harpy",
    "hedgehog",
    "hedgehog man",
    "helmet snake",
    "herring",
    "hippo",
    "hippo man",
    "hoary marmot",
    "hoary marmot man",
    "honey badger",
    "honey badger man",
    "honey bee",
    "hornbill",
    "hornbill man",
    "horse",
    "horseshoe crab",
    "horseshoe crab man",
    "human",
    "hungry head",
    "hydra",
    "hyena",
    "hyena man",
    "ibex",
    "ibex man",
    "ice wolf",
    "iguana",
    "iguana man",
    "impala",
    "impala man",
    "infected ghoul",
    "intelligent undead",
    "iron man",
    "jabberer",
    "jackal",
    "jackal man",
    "jaguar",
    "jaguar man",
    "jumping spider",
    "jumping spider man",
    "kakapo",
    "kakapo man",
    "kangaroo",
    "kangaroo man",
    "kea",
    "kea man",
    "kestrel",
    "kestrel man",
    "king cobra",
    "king cobra man",
    "kingsnake",
    "kingsnake man",
    "kiwi",
    "kiwi man",
    "knuckle worm",
    "koala",
    "koala man",
    "kobold",
    "large rat",
    "large roach",
    "leech",
    "leech man",
    "leopard",
    "leopard gecko",
    "leopard gecko man",
    "leopard man",
    "leopard seal",
    "leopard seal man",
    "lion",
    "lion man",
    "lion tamarin",
    "lion tamarin man",
    "little penguin",
    "lizard",
    "lizard man",
    "llama",
    "longfin mako shark",
    "longnose gar",
    "loon",
    "loon man",
    "lorikeet",
    "lorikeet man",
    "louse",
    "louse man",
    "lungfish",
    "lynx",
    "lynx man",
    "mackerel",
    "magma crab",
    "magma man",
    "magpie",
    "magpie man",
    "mandrill",
    "mandrill man",
    "manera",
    "manta ray",
    "mantis",
    "mantis man",
    "marlin",
    "masked lovebird",
    "masked lovebird man",
    "merperson",
    "milkfish",
    "mink",
    "mink man",
    "minotaur",
    "moghopper",
    "molemarian",
    "monarch butterfly",
    "monarch butterfly man",
    "mongoose",
    "mongoose man",
    "monitor lizard",
    "monitor lizard man",
    "moon snail",
    "moon snail man",
    "moose",
    "moose man",
    "mosquito",
    "mosquito man",
    "moth",
    "moth man",
    "mountain gnome",
    "mountain goat",
    "mountain goat man",
    "mud man",
    "mule",
    "mummy",
    "muskox",
    "muskox man",
    "mussel",
    "naked mole dog",
    "narwhal",
    "narwhal man",
    "nautilus",
    "nautilus man",
    "necromancer",
    "night troll",
    "nightmare",
    "nightwing",
    "nurse shark",
    "ocean sunfish",
    "ocelot",
    "ocelot man",
    "octopus",
    "octopus man",
    "ogre",
    "olm",
    "olm man",
    "one-humped camel",
    "one-humped camel man",
    "opah",
    "opossum",
    "opossum man",
    "orangutan",
    "orca",
    "orca man",
    "oriole",
    "oriole man",
    "osprey",
    "osprey man",
    "ostrich",
    "ostrich man",
    "otter man",
    "oyster",
    "panda",
    "panda man",
    "pangolin",
    "pangolin man",
    "parakeet",
    "parakeet man",
    "peach-faced lovebird",
    "peach-faced lovebird man",
    "penguin",
    "penguin man",
    "perch",
    "peregrine falcon",
    "peregrine falcon man",
    "phantom spider",
    "pig",
    "pike",
    "pike (fish)",
    "pileated gibbon",
    "pixie",
    "platypus",
    "platypus man",
    "plump helmet man",
    "polar bear",
    "polar bear man",
    "pond grabber",
    "pond turtle",
    "pond turtle man",
    "porcupine",
    "porcupine man",
    "puffin",
    "puffin man",
    "purring maggot",
    "python",
    "python man",
    "rabbit",
    "raccoon",
    "raccoon man",
    "rainbow trout",
    "rat",
    "rat man",
    "rattlesnake",
    "rattlesnake man",
    "raven",
    "raven man",
    "reacher",
    "red panda",
    "red panda man",
    "red squirrel",
    "red squirrel man",
    "red-winged blackbird",
    "red-winged blackbird man",
    "reindeer",
    "reptile man",
    "rhesus macaque",
    "rhesus macaque man",
    "rhinoceros",
    "rhinoceros man",
    "river otter",
    "roach man",
    "roc",
    "rodent man",
    "rutherer",
    "sailfin molly",
    "salmon",
    "saltwater crocodile",
    "saltwater crocodile man",
    "sasquatch",
    "satyr",
    "sea lamprey",
    "sea monster",
    "sea nettle jellyfish",
    "sea otter",
    "sea serpent",
    "seahorse",
    "serpent man",
    "shad",
    "shark",
    "sheep",
    "shortfin mako shark",
    "siamang",
    "silvery gibbon",
    "skink",
    "skink man",
    "skunk",
    "skunk man",
    "sloth",
    "sloth bear",
    "sloth bear man",
    "sloth man",
    "slug",
    "slug man",
    "snail",
    "snail man",
    "snapping turtle man",
    "snowy owl",
    "snowy owl man",
    "sole",
    "sparrow",
    "sparrow man",
    "sperm whale",
    "sperm whale man",
    "spider monkey",
    "spider monkey man",
    "spiny dogfish",
    "sponge",
    "sponge man",
    "spotted ratfish",
    "spotted wobbegong",
    "squid",
    "squid man",
    "steelhead trout",
    "stingray",
    "stoat",
    "stoat man",
    "strangler",
    "sturgeon",
    "swan",
    "swan man",
    "swordfish",
    "tapir",
    "tapir man",
    "termite",
    "thornback ray",
    "thrips",
    "thrips man",
    "tick",
    "tick man",
    "tiger",
    "tiger man",
    "tiger shark",
    "tigerfish",
    "toad",
    "toad man",
    "troglodyte",
    "troll",
    "turkey",
    "two-humped camel",
    "two-humped camel man",
    "two-legged rhino lizard",
    "unicorn",
    "vampire",
    "voracious cave crawler",
    "vulture",
    "vulture man",
    "wagon",
    "walrus",
    "walrus man",
    "warthog",
    "warthog man",
    "water buffalo",
    "weasel",
    "weasel man",
    "werebeast",
    "whale shark",
    "white stork",
    "white stork man",
    "white-browed gibbon",
    "white-handed gibbon",
    "white-spotted puffer",
    "whitetip reef shark",
    "wild boar",
    "wild boar man",
    "wolf",
    "wolf man",
    "wolverine",
    "wolverine man",
    "wombat",
    "wombat man",
    "worm",
    "worm man",
    "wren",
    "wren man",
    "yak",
    "yellow bullhead",
    "yeti",
]
