import random

creatures = [
    "aardvark",
    "aardvarkman",
    "acorn fly",
    "adder",
    "adderman",
    "albatross",
    "albatrossman",
    "alligator",
    "alligatorman",
    "alligator snapping turtle",
    "alpaca",
    "amethystman",
    "amphibianman",
    "anaconda",
    "anacondaman",
    "anchovy",
    "angel",
    "angelshark",
    "animated dead",
    "anole",
    "anoleman",
    "ant",
    "antman",
    "armadillo",
    "armadilloman",
    "axolotl",
    "axolotlman",
    "aye-aye",
    "aye-ayeman",
    "badger",
    "badgerman",
    "banded knifefish",
    "bark scorpion",
    "bark scorpionman",
    "barn owl",
    "barn owlman",
    "basking shark",
    "bat",
    "batman",
    "bat ray",
    "beak dog",
    "beaver",
    "beaverman",
    "beetle",
    "beetleman",
    "bilou",
    "black bear",
    "black bearman",
    "black bullhead",
    "black mamba",
    "black mambaman",
    "black-crested gibbon",
    "black-handed gibbon",
    "blacktip reef shark",
    "blind cave bear",
    "blind cave ogre",
    "blizzardman",
    "blood gnat",
    "bloodman",
    "blue jay",
    "blue peafowl",
    "blue shark",
    "bluefin tuna",
    "bluefish",
    "bluejayman",
    "bobcat",
    "bobcatman",
    "bogeyman",
    "bonobo",
    "bronze colossus",
    "brook lamprey",
    "brown bullhead",
    "brown recluse spider",
    "brown recluse spiderman",
    "bugbat",
    "bull shark",
    "bumblebee",
    "bushmaster",
    "bushmasterman",
    "bushtit",
    "bushtitman",
    "buzzard",
    "buzzardman",
    "camel",
    "cap hopper",
    "captured live fish",
    "capuchin",
    "capuchinman",
    "capybara",
    "capybaraman",
    "cardinal",
    "cardinalman",
    "carp",
    "cassowary",
    "cassowaryman",
    "cat",
    "cave blob",
    "cave crocodile",
    "cave dragon",
    "cave fish",
    "cave fishman",
    "cave floater",
    "cave lobster",
    "cave spider",
    "cave swallow",
    "cave swallowman",
    "cavy",
    "centaur",
    "chameleon",
    "chameleonman",
    "char",
    "cheetah",
    "cheetahman",
    "chicken",
    "chimera",
    "chimpanzee",
    "chinchilla",
    "chinchillaman",
    "chipmunk",
    "chipmunkman",
    "clown loach",
    "clownfish",
    "coati",
    "coatiman",
    "cockatiel",
    "cockatielman",
    "cod",
    "coelacanth",
    "common skate",
    "common snapping turtle",
    "conger eel",
    "copperhead snake",
    "copperhead snakeman",
    "cougar",
    "cougarman",
    "cow",
    "coyote",
    "coyoteman",
    "crab",
    "crabman",
    "creeping eye",
    "creepy crawler",
    "crow",
    "crowman",
    "crundle",
    "cuttlefish",
    "cuttlefishman",
    "cyclops",
    "damselfly",
    "damselflyman",
    "dark gnome",
    "deer",
    "deerman",
    "demon",
    "demon rat",
    "desert tortoise",
    "desert tortoiseman",
    "dingo",
    "dingoman",
    "dog",
    "donkey",
    "dragon",
    "dragonfly",
    "dragonflyman",
    "draltha",
    "drunian",
    "duck",
    "dwarf",
    "eagle",
    "eagleman",
    "echidna",
    "echidnaman",
    "elephant",
    "elephantman",
    "elephant seal",
    "elephant sealman",
    "elf",
    "elk",
    "elk bird",
    "elkman",
    "emperor penguin",
    "emu",
    "emuman",
    "ettin",
    "experiment",
    "fairy",
    "fire imp",
    "fireman",
    "fire snake",
    "firefly",
    "fireflyman",
    "flesh ball",
    "floating guts",
    "flounder",
    "fluffy wambler",
    "fly",
    "flyman",
    "flying squirrel",
    "flying squirrelman",
    "foul blendec",
    "fox",
    "foxman",
    "fox squirrel",
    "frill shark",
    "gabbroman",
    "gazelle",
    "gazelleman",
    "ghost",
    "giant",
    "giant aardvark",
    "giant adder",
    "giant albatross",
    "giant alligator",
    "giant anaconda",
    "giant anole",
    "giant armadillo",
    "giant axolotl",
    "giant aye-aye",
    "giant badger",
    "giant bark scorpion",
    "giant barn owl",
    "giant bat",
    "giant beaver",
    "giant beetle",
    "giant black bear",
    "giant black mamba",
    "giant bluejay",
    "giant bobcat",
    "giant brown recluse spider",
    "giant bushmaster",
    "giant bushtit",
    "giant buzzard",
    "giant capuchin",
    "giant capybara",
    "giant cardinal",
    "giant cassowary",
    "giant cave spider",
    "giant cave swallow",
    "giant cave toad",
    "giant chameleon",
    "giant cheetah",
    "giant chinchilla",
    "giant chipmunk",
    "giant coati",
    "giant cockatiel",
    "giant copperhead snake",
    "giant cougar",
    "giant coyote",
    "giant crab",
    "giant crow",
    "giant cuttlefish",
    "giant damselfly",
    "giant deer",
    "giant desert scorpion",
    "giant desert tortoise",
    "giant dingo",
    "giant dragonfly",
    "giant eagle",
    "giant earthworm",
    "giant echidna",
    "giant elephant",
    "giant elephant seal",
    "giant elk",
    "giant emu",
    "giant firefly",
    "giant fly",
    "giant flying squirrel",
    "giant fox",
    "giant gazelle",
    "giant gila monster",
    "giant giraffe",
    "giant grackle",
    "giant grasshopper",
    "giant gray langur",
    "giant gray squirrel",
    "giant great horned owl",
    "giant green tree frog",
    "giant grey parrot",
    "giant grizzly bear",
    "giant groundhog",
    "giant grouper",
    "giant hamster",
    "giant hare",
    "giant harp seal",
    "giant hedgehog",
    "giant hippo",
    "giant hoary marmot",
    "giant honey badger",
    "giant hornbill",
    "giant horseshoe crab",
    "giant hyena",
    "giant ibex",
    "giant iguana",
    "giant impala",
    "giant jackal",
    "giant jaguar",
    "giant jumping spider",
    "giant kakapo",
    "giant kangaroo",
    "giant kea",
    "giant kestrel",
    "giant king cobra",
    "giant kingsnake",
    "giant kiwi",
    "giant koala",
    "giant leech",
    "giant leopard",
    "giant leopard gecko",
    "giant leopard seal",
    "giant lion",
    "giant lion tamarin",
    "giant lizard",
    "giant loon",
    "giant lorikeet",
    "giant louse",
    "giant lynx",
    "giant magpie",
    "giant mandrill",
    "giant mantis",
    "giant masked lovebird",
    "giant mink",
    "giant mole",
    "giant monarch butterfly",
    "giant mongoose",
    "giant monitor lizard",
    "giant moon snail",
    "giant moose",
    "giant mosquito",
    "giant moth",
    "giant mountain goat",
    "giant muskox",
    "giant narwhal",
    "giant nautilus",
    "giant ocelot",
    "giant octopus",
    "giant olm",
    "giant one-humped camel",
    "giant opossum",
    "giant orca",
    "giant oriole",
    "giant osprey",
    "giant ostrich",
    "giant otter",
    "giant pangolin",
    "giant parakeet",
    "giant peach-faced lovebird",
    "giant penguin",
    "giant peregrine falcon",
    "giant platypus",
    "giant polar bear",
    "giant pond turtle",
    "giant porcupine",
    "giant puffin",
    "giant python",
    "giant raccoon",
    "giant rat",
    "giant rattlesnake",
    "giant raven",
    "giant red panda",
    "giant red squirrel",
    "giant red-winged blackbird",
    "giant rhesus macaque",
    "giant rhinoceros",
    "giant roach",
    "giant saltwater crocodile",
    "giant skink",
    "giant skunk",
    "giant sloth",
    "giant sloth bear",
    "giant slug",
    "giant snail",
    "giant snapping turtle",
    "giant snowy owl",
    "giant sparrow",
    "giant sperm whale",
    "giant spider monkey",
    "giant sponge",
    "giant stoat",
    "giant swan",
    "giant tapir",
    "giant thrips",
    "giant tick",
    "giant tiger",
    "giant toad",
    "giant tortoise",
    "giant tortoiseman",
    "giant two-humped camel",
    "giant vulture",
    "giant walrus",
    "giant warthog",
    "giant weasel",
    "giant white stork",
    "giant wild boar",
    "giant wolf",
    "giant wolverine",
    "giant wombat",
    "giant wren",
    "gigantic panda",
    "gigantic squid",
    "gigantic tortoise",
    "gila monster",
    "gila monsterman",
    "giraffe",
    "giraffeman",
    "glasseye",
    "goat",
    "goblin",
    "goose",
    "gorilla",
    "gorlak",
    "grackle",
    "grackleman",
    "grasshopper",
    "grasshopperman",
    "gray gibbon",
    "gray langur",
    "gray langurman",
    "gray squirrel",
    "gray squirrelman",
    "great barracuda",
    "great horned owl",
    "great horned owlman",
    "great white shark",
    "green devourer",
    "green tree frog",
    "green tree frogman",
    "gremlin",
    "grey parrot",
    "grey parrotman",
    "griffon",
    "grimeling",
    "grizzly bear",
    "grizzly bearman",
    "groundhog",
    "groundhogman",
    "guineafowl",
    "guppy",
    "hagfish",
    "hake",
    "halibut",
    "hammerhead shark",
    "hamster",
    "hamsterman",
    "hare",
    "hareman",
    "harp seal",
    "harp sealman",
    "harpy",
    "hedgehog",
    "hedgehogman",
    "helmet snake",
    "herring",
    "hippo",
    "hippoman",
    "hoary marmot",
    "hoary marmotman",
    "honey badger",
    "honey badgerman",
    "honey bee",
    "hornbill",
    "hornbillman",
    "horse",
    "horseshoe crab",
    "horseshoe crabman",
    "human",
    "hungry head",
    "hydra",
    "hyena",
    "hyenaman",
    "ibex",
    "ibexman",
    "ice wolf",
    "iguana",
    "iguanaman",
    "impala",
    "impalaman",
    "infected ghoul",
    "intelligent undead",
    "ironman",
    "jabberer",
    "jackal",
    "jackalman",
    "jaguar",
    "jaguarman",
    "jumping spider",
    "jumping spiderman",
    "kakapo",
    "kakapoman",
    "kangaroo",
    "kangarooman",
    "kea",
    "keaman",
    "kestrel",
    "kestrelman",
    "king cobra",
    "king cobraman",
    "kingsnake",
    "kingsnakeman",
    "kiwi",
    "kiwiman",
    "knuckle worm",
    "koala",
    "koalaman",
    "kobold",
    "large rat",
    "large roach",
    "leech",
    "leechman",
    "leopard",
    "leopard gecko",
    "leopard geckoman",
    "leopardman",
    "leopard seal",
    "leopard sealman",
    "lion",
    "lionman",
    "lion tamarin",
    "lion tamarinman",
    "little penguin",
    "lizard",
    "lizardman",
    "llama",
    "longfin mako shark",
    "longnose gar",
    "loon",
    "loonman",
    "lorikeet",
    "lorikeetman",
    "louse",
    "louseman",
    "lungfish",
    "lynx",
    "lynxman",
    "mackerel",
    "magma crab",
    "magmaman",
    "magpie",
    "magpieman",
    "mandrill",
    "mandrillman",
    "manera",
    "manta ray",
    "mantis",
    "mantisman",
    "marlin",
    "masked lovebird",
    "masked lovebirdman",
    "merperson",
    "milkfish",
    "mink",
    "minkman",
    "minotaur",
    "moghopper",
    "molemarian",
    "monarch butterfly",
    "monarch butterflyman",
    "mongoose",
    "mongooseman",
    "monitor lizard",
    "monitor lizardman",
    "moon snail",
    "moon snailman",
    "moose",
    "mooseman",
    "mosquito",
    "mosquitoman",
    "moth",
    "mothman",
    "mountain gnome",
    "mountain goat",
    "mountain goatman",
    "mudman",
    "mule",
    "mummy",
    "muskox",
    "muskoxman",
    "mussel",
    "naked mole dog",
    "narwhal",
    "narwhalman",
    "nautilus",
    "nautilusman",
    "necromancer",
    "night troll",
    "nightmare",
    "nightwing",
    "nurse shark",
    "ocean sunfish",
    "ocelot",
    "ocelotman",
    "octopus",
    "octopusman",
    "ogre",
    "olm",
    "olmman",
    "one-humped camel",
    "one-humped camelman",
    "opah",
    "opossum",
    "opossumman",
    "orangutan",
    "orca",
    "orcaman",
    "oriole",
    "orioleman",
    "osprey",
    "ospreyman",
    "ostrich",
    "ostrichman",
    "otterman",
    "oyster",
    "panda",
    "pandaman",
    "pangolin",
    "pangolinman",
    "parakeet",
    "parakeetman",
    "peach-faced lovebird",
    "peach-faced lovebirdman",
    "penguin",
    "penguinman",
    "perch",
    "peregrine falcon",
    "peregrine falconman",
    "phantom spider",
    "pig",
    "pike",
    "pike (fish)",
    "pileated gibbon",
    "pixie",
    "platypus",
    "platypusman",
    "plump helmetman",
    "polar bear",
    "polar bearman",
    "pond grabber",
    "pond turtle",
    "pond turtleman",
    "porcupine",
    "porcupineman",
    "puffin",
    "puffinman",
    "purring maggot",
    "python",
    "pythonman",
    "rabbit",
    "raccoon",
    "raccoonman",
    "rainbow trout",
    "rat",
    "ratman",
    "rattlesnake",
    "rattlesnakeman",
    "raven",
    "ravenman",
    "reacher",
    "red panda",
    "red pandaman",
    "red squirrel",
    "red squirrelman",
    "red-winged blackbird",
    "red-winged blackbirdman",
    "reindeer",
    "reptileman",
    "rhesus macaque",
    "rhesus macaqueman",
    "rhinoceros",
    "rhinocerosman",
    "river otter",
    "roachman",
    "roc",
    "rodentman",
    "rutherer",
    "sailfin molly",
    "salmon",
    "saltwater crocodile",
    "saltwater crocodileman",
    "sasquatch",
    "satyr",
    "sea lamprey",
    "sea monster",
    "sea nettle jellyfish",
    "sea otter",
    "sea serpent",
    "seahorse",
    "serpentman",
    "shad",
    "shark",
    "sheep",
    "shortfin mako shark",
    "siamang",
    "silvery gibbon",
    "skink",
    "skinkman",
    "skunk",
    "skunkman",
    "sloth",
    "sloth bear",
    "sloth bearman",
    "slothman",
    "slug",
    "slugman",
    "snail",
    "snailman",
    "snapping turtleman",
    "snowy owl",
    "snowy owlman",
    "sole",
    "sparrow",
    "sparrowman",
    "sperm whale",
    "sperm whaleman",
    "spider monkey",
    "spider monkeyman",
    "spiny dogfish",
    "sponge",
    "spongeman",
    "spotted ratfish",
    "spotted wobbegong",
    "squid",
    "squidman",
    "steelhead trout",
    "stingray",
    "stoat",
    "stoatman",
    "strangler",
    "sturgeon",
    "swan",
    "swanman",
    "swordfish",
    "tapir",
    "tapirman",
    "termite",
    "thornback ray",
    "thrips",
    "thripsman",
    "tick",
    "tickman",
    "tiger",
    "tigerman",
    "tiger shark",
    "tigerfish",
    "toad",
    "toadman",
    "troglodyte",
    "troll",
    "turkey",
    "two-humped camel",
    "two-humped camelman",
    "two-legged rhino lizard",
    "unicorn",
    "vampire",
    "voracious cave crawler",
    "vulture",
    "vultureman",
    "wagon",
    "walrus",
    "walrusman",
    "warthog",
    "warthogman",
    "water buffalo",
    "weasel",
    "weaselman",
    "werebeast",
    "whale shark",
    "white stork",
    "white storkman",
    "white-browed gibbon",
    "white-handed gibbon",
    "white-spotted puffer",
    "whitetip reef shark",
    "wild boar",
    "wild boarman",
    "wolf",
    "wolfman",
    "wolverine",
    "wolverineman",
    "wombat",
    "wombatman",
    "worm",
    "wormman",
    "wren",
    "wrenman",
    "yak",
    "yellow bullhead",
    "yeti",
]


def create_random_creature():
    return random.choice(creatures)
